# Generated by Django 4.2.1 on 2023-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
